name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: codacy-analysis-cli
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: mrfyda/codacy-analysis-cli-action@master
        with:
          project-token: 31c35d5eff9a4a138b879e52f615129f
          
      - name: Run codacy-coverage-reporter final
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: 31c35d5eff9a4a138b879e52f615129f
